# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: MSBuild

on:
  push:
    branches:
      - master

env:
  # Path to the solution file relative to the root of the project.
  SOLUTION_FILE_PATH: .

  # Configuration type to build.
  # You can convert this to a build matrix if you need coverage of multiple configuration types.
  # https://docs.github.com/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
  BUILD_CONFIGURATION: Release

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.0.2

      - name: Restore NuGet packages
        run: nuget restore ${{ github.workspace }}

      - name: Debug Build
        if: github.ref == 'refs/heads/master' && matrix.config == 'Debug'
        run: msbuild /m /p:Configuration=Debug ${{ github.workspace }}

      - name: Release Build
        if: github.ref == 'refs/heads/master' && matrix.config == 'Release'
        run: msbuild /m /p:Configuration=Release ${{ github.workspace }}
